static-resource:
  paths:
    '[/**]':
      - classpath:/
      - classpath:/multishop-ui/
      - classpath:/public/
      - classpath:/static/
      - file:///c:/upload-dir/
#      - file:///home/rahmati/upload_dir/
    '[/assets]':
      - file:///c:/upload-dir/
#      - file:///home/rahmati/upload_dir/
